### ISSUE TITLE
Int datatype

### ISSUE THREAD

**Issue by AlexandreRio** [kevoree-modeling/idea-plugin#4]
The editor is expecting `Integer` datatype for mm files while the compiler is expecting `Int`.
KMF version: 4.27.0.2
Kevoree plugin version: 29

**Comment by lmouline** [comment]
the editor is outdated, a new version should come, soon :)

**Comment by AlexandreRio** [comment]
Oh I see, another quick question: is it possible to generate code from an ecore file instead of a mm file?
The following code, unfortunately, doesn't work:
```
<configuration>
    <metaModelFile>model/model.ecore</metaModelFile>
</configuration>
```

**Comment by lmouline** [comment]
Not, @dukeboard  will confirm that (or not), but the support of ECore has been dropped since a long time.

Btw, you should use this project: https://github.com/datathings/greycat
It is the new version of KMF :)

The new IDEA Plugin should be presented in this project :)

**Comment by dukeboard** [comment]
Hi Alexandro, sorry for the answer delay and many thanks for your interest to our tools.
Ludovic is right we haven't used the Ecore to .mm since a while but with 2 minor adjustments it can be done. We are in the process to publish the new documentation for GreyCat Modelling  framework (successor of Kevoree Modelling). Overall the full process will be way easier. I keep you updated in the coming days about this update of both plugin and GreyCat framework.

**Comment by AlexandreRio** [comment]
Hi François, thanks for keeping me in touch. I thought GreyCat was a new project you were working on and not a successor of Kevoree. I really think it's the right tool for me, can't wait to read more from you :-)
